suppress gunicorn error which is being caught by errortracker.  The gunicorn error is of this form:
Traceback (most recent call last):
  File "/home/ike/mitx_all/python/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 33, in run
    client, addr = self.socket.accept()
  File "/usr/lib/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable